### ISSUE TITLE
What about common classes?

### ISSUE THREAD

**Issue by ghost** [VictorAlbertos/DirtyAndroid#3]
Hi.
Very interesting packaging structure!
I've started refactoring my project but soon i realized that some classes are common for data and presentation (ex: Utils).
What you will do with common classes? One thing that coming in my mind to have Utils classes in data and in presentation separately. Or to add "common" package.

P.S. Can be fondation = core and sections = features ?

Thanks!

**Comment by VictorAlbertos** [comment]
That's weird. The responsibilities between layers should not require code crossing boundaries. But if that's the case, I would create another package. Probably you want to create some sort of library to encapsulate these common functionalities.
